### ISSUE TITLE
contact me

### ISSUE THREAD

**Issue by goozang-records** [derekjohnsonva/cs2150Labs#1]
Yo, send me an email at amar@parity.io or asinghchrony@protonmail.com and let's chat. I want to see how you're doing and discuss some opportunities that you might be interested in.

I tried to get other people to connect us, but everyone at UVA (who I already know) is really unresponsive.

**Comment by derekjohnsonva** [comment]
How's it going man,
My cell is 703-953-4756 if that is easier. Free in the evenings most days.
